### PR TITLE
UX - Set variable in the project when loading layers with the openADS URL

### PR DESCRIPTION
**Pull request by Gustry**
Ticket 23

### CODE REVIEW

**Comment by rldhont** [comment]
Can you add a check for URL_ADS ? It has to be set without parameters and  anchor

**Comment by Gustry** [comment]
The URL was updated on runtime.
Now, the execution will be stopped if the URL is not correct.

**Comment by rldhont** [comment]
Can you add a check for URL_ADS ? It has to be set without parameters and  anchor

**Comment by rldhont** [comment]
Sorry for the duplicated message, an error in the interface

**Review by rldhont — APPROVED** [review]

**Pull request merged**
